package partsimport

import _ "embed"

// TemplateXLSX is the workbook users download, fill in and upload back. It is
// generated by scripts/generate-parts-import-template.py and embedded so the
// file the server hands out can never drift from the columns Parse expects.
//
//go:embed parts_import_template.xlsx
var TemplateXLSX []byte

// TemplateFilename is the name the browser saves the download as.
const TemplateFilename = "เทมเพลตเพิ่มสินค้า.xlsx"
