package handlers

import (
	"net/http"
	"strconv"

	"backend/internal/config"
	"backend/internal/repository"

	"github.com/gin-gonic/gin"
)

type POSHandler struct {
	pos repository.POSRepository
}

func NewPOSHandler(pos repository.POSRepository) *POSHandler {
	return &POSHandler{pos: pos}
}

func (h *POSHandler) List(c *gin.Context) {
	limit := config.DefaultLimit
	offset := config.DefaultOffset

	if v := c.Query("limit"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 && n <= config.MaxLimit {
			limit = n
		}
	}
	if v := c.Query("offset"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n >= 0 {
			offset = n
		}
	}

	posList, err := h.pos.List(c.Request.Context(), limit, offset)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed_to_list_pos"})
		return
	}

	out := make([]gin.H, 0, len(posList))
	for _, p := range posList {
		out = append(out, gin.H{
			"posId":    p.POSID,
			"branchId": p.BranchID,
			"posName":  p.POSName,
			"isActive": p.IsActive,
			// posSecret is not returned in list
		})
	}

	c.JSON(http.StatusOK, gin.H{
		"pos": out,
	})
}

func (h *POSHandler) Get(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "missing_pos_id"})
		return
	}

	pos, err := h.pos.GetByID(c.Request.Context(), id)
	if err != nil {
		if repository.IsNotFoundError(err) {
			c.JSON(http.StatusNotFound, gin.H{"error": "pos_not_found"})
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed_to_get_pos"})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"posId":    pos.POSID,
		"branchId": pos.BranchID,
		"posName":  pos.POSName,
		"isActive": pos.IsActive,
		// posSecret is not returned in GET
	})
}

func (h *POSHandler) Create(c *gin.Context) {
	var req struct {
		POSID    string `json:"posId" binding:"required"`
		BranchID string `json:"branchId" binding:"required"`
		POSName  string `json:"posName" binding:"required"`
	}

	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid_request"})
		return
	}

	pos := &repository.POS{
		POSID:    req.POSID,
		BranchID: req.BranchID,
		POSName:  req.POSName,
		IsActive: true, // Default to active when creating
		// POSSecret will be generated by repository.Create
	}

	if err := h.pos.Create(c.Request.Context(), pos); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed_to_create_pos"})
		return
	}

	c.JSON(http.StatusCreated, gin.H{
		"posId":    pos.POSID,
		"branchId": pos.BranchID,
		"posName":  pos.POSName,
		"isActive": pos.IsActive,
		// posSecret is not returned in response (use GET /pos/:id/secret to retrieve)
	})
}

func (h *POSHandler) ToggleActivate(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "missing_pos_id"})
		return
	}

	if err := h.pos.ToggleActive(c.Request.Context(), id); err != nil {
		if repository.IsNotFoundError(err) {
			c.JSON(http.StatusNotFound, gin.H{"error": "pos_not_found"})
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed_to_toggle_pos"})
		return
	}

	// Get updated POS to return current status
	pos, err := h.pos.GetByID(c.Request.Context(), id)
	if err != nil {
		if repository.IsNotFoundError(err) {
			c.JSON(http.StatusNotFound, gin.H{"error": "pos_not_found"})
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed_to_get_pos"})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"posId":    pos.POSID,
		"branchId": pos.BranchID,
		"posName":  pos.POSName,
		"isActive": pos.IsActive,
	})
}

func (h *POSHandler) GetSecret(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "missing_pos_id"})
		return
	}

	secret, err := h.pos.GetSecret(c.Request.Context(), id)
	if err != nil {
		if repository.IsNotFoundError(err) {
			c.JSON(http.StatusNotFound, gin.H{"error": "pos_not_found"})
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed_to_get_pos_secret"})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"posId":     id,
		"posSecret": secret,
	})
}

func (h *POSHandler) RefreshSecret(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "missing_pos_id"})
		return
	}

	newSecret, err := h.pos.RefreshSecret(c.Request.Context(), id)
	if err != nil {
		if repository.IsNotFoundError(err) {
			c.JSON(http.StatusNotFound, gin.H{"error": "pos_not_found"})
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed_to_refresh_pos_secret"})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"posId":     id,
		"posSecret": newSecret,
		"message":   "POS secret refreshed successfully",
	})
}

func (h *POSHandler) Delete(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "missing_pos_id"})
		return
	}

	if err := h.pos.Delete(c.Request.Context(), id); err != nil {
		if repository.IsNotFoundError(err) {
			c.JSON(http.StatusNotFound, gin.H{"error": "pos_not_found"})
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed_to_delete_pos"})
		return
	}

	c.JSON(http.StatusOK, gin.H{"message": "pos_deleted"})
}

